### ISSUE TITLE
Kursteilnehmer hinzufügen

### ISSUE THREAD

**Issue by Necktschnagge** [Necktschnagge/cpp-course-project-01#1]
Jeder Kursteilnehmer soll hier in den Kommentar seinen Vornamen schreiben,
damit ich zum einen über euren automatisch hinterlegten Account euch Schreibrechte gewähren kann,
und damit ich zum anderen euch gleich besser zuordnen kann

**Comment by ghost** [comment]
Lukas

**Comment by hmfrank** [comment]
Hannes

**Comment by SchermulyM** [comment]
Matthias

**Comment by DavidLokison** [comment]
David

**Comment by Yttrium95** [comment]
Jonas
