### ISSUE TITLE
Arbeitsweise

### ISSUE THREAD

**Issue by Necktschnagge** [Necktschnagge/cpp-course-project-01#2]
Das erste Projekt erledigt im Grunde jeder für sich.
[D.h. nicht, dass gegenseitige Unterstützung verboten ist, aber dieses Projekt ist nicht von Grund auf als Gruppenprojekt geplant]

Jeder legt sich einen eigenen Branch an. Dieser ist so zu nennen wie euer Vorname lautet.

Jeder Teilnehmer commited ausschließlich in seinem Branch! Auf dem Master steht jederzeit die clean-Version (vorbereitete Projektverzeichnisse ohne implementierung) bereit.

Es wird darum gebeten, so relativ häufig (aber sinnig!!!) zu committen, damit jeder Teilnehmer stets den Stand der anderen betrachten kann und es zu den Treffen des Kurses einfacher möglich ist, die Arbeit einzelner Studenten am Beamer zu zeigen und ggf. zu diskutieren.
Code-Review soll ein wichtiger Bestandteil werden, sodass ihr lernt, anderen Code nachzuvollziehen und die Möglichkeit habt, euren Lösungsansatz mit anderen zu vergleichen

**Comment by hmfrank** [comment]
Hi, ich hab ne Lösung aber hab noch keine Berechtigung zum Pushen.

**Comment by Necktschnagge** [comment]
@hmfrank 
https://github.com/Necktschnagge/cpp-course-project-01/invitations
Du stehst bei mir als ~~"Anfrage abgeschickt, aber noch nicht bestätigt" drin.
Schau mal bei dem Link, vielleicht kannst du da bestätigen?

**Comment by Necktschnagge** [comment]
Im übrigen. Wenn Fragen sind etc. ...
**Scheut euch nie, ein Issue zu eröffnen!!!**
