### ISSUE TITLE
Branch Hannes (Suche nach einer Musterlösung)

### ISSUE THREAD

**Issue by Necktschnagge** [Necktschnagge/cpp-course-project-01#4]
Also @hmfrank hat schon eine schöne Lösung implementiert.
Zumindest hat es bei ihm funktioniert, meinte er.

Nur da ist leider lauter C-spezifisches drin, was unter C++ nicht compiliert. Auweia.
Aber vom Konzept her sieht es schon mal gut strukturiert aus.

Sag mal, @hmfrank, wie kompiliert das denn bei dir überhaupt???

**Comment by hmfrank** [comment]
Ich habs die ganze Zeit mit der IDE (CLion) kompiliert.
Kann ja mal schaun ob ich die C-spezifischen Sachen noch raus kriege, sodass es auch mit Make kompiliert.

**Comment by Necktschnagge** [comment]
bug report:
Gibt man bei hannes lösung 13x3 und 3x13 ein, oder 14x3 und 3x14.

gefunden von @MaxMatti

(PS ich habe es nicht nachgeprüft)

**Comment by MaxMatti** [comment]
Ich arbeite mit leicht modifizierten Versionen, weil ich dadurch die Zeit besser messen kann. Meine Main-Funktion sieht so aus:

	int main(int argc, char* argv[]) {
		if (argc > 2) {
			unsigned int height = stoi(std::string(argv[1])), width = stoi(std::string(argv[2]));
			unsigned int solution = solve(height, width);
			std::cout << "Solution: " << solution << "\n";
		} else {
			std::cout << "Give me 2 Integers!\n";
		}
	    return 0;
	}

Bei der Version vom "Hannes" Branch:

	time ./Project1 4 12 && time ./Project1 12 4
	Solution: 1895145
	./Project1 4 12  38,03s user 0,03s system 98% cpu 38,824 total
	Solution: 831
	./Project1 12 4  0,02s user 0,00s system 84% cpu 0,020 total

Bei meiner:

	time ./parkettieren 4 12 && time ./parkettieren 12 4
	Solution: 1895145
	./parkettieren 4 12  21,67s user 0,00s system 99% cpu 21,744 total
	Solution: 1895145
	./parkettieren 12 4  21,74s user 0,00s system 99% cpu 21,801 total

Da die Zahlen nicht übereinstimmen, muss da irgendwo ein Fehler vorliegen.

**Comment by Necktschnagge** [comment]
Hannes' Version ist mittlerweile auch komplett C++ kompatibel.
Für ne Musterlösung würde ich mir wünschen, dass die Makros da wegkommen.
EDIT: und wenn bug gefixt und Funktionssignatur wieder zurückgeändert, falls jemand auf anderer IDE kompilieren will

**Comment by Necktschnagge** [comment]
Ich habe auch eine Musterlösung in Arbeit, aber wie gesagt noch _in Arbeit_
