### ISSUE TITLE
Musterlösung Tutor

### ISSUE THREAD

**Issue by Necktschnagge** [Necktschnagge/cpp-course-project-01#6]
* Ich habe jetzt eine Musterlösung fertig.
* will diese vielleicht noch verbessern (Performance)
* Musterlösung wird erstmal nicht gepusht: Es geht nicht darum, dass ihr die Musterlösung kennt, sondern dass ihr kreativ programmiert und Strategien entwickelt

Vielen Dank @Shildifreak für die verschiedenen Ideen zur Problemlösung und einen konkreten Algorithmus, der relativ sehr effizient ist, den ich nur noch in C++ umsetzen musste, und dessen Implementation ich noch etwas verbessern könnte.

**Comment by Necktschnagge** [comment]
aktuelle Probleme:

* einbinden irgendeiner Big Integer Lösung für C++ um Felder mit 12*13 zB. zu ermöglichen
* verbessern der Laufzeit kritischer Schleifendurchläufe (refactoring)
* (bisher keinerlei Garantie auf bug Freiheit)

**Comment by MaxMatti** [comment]
Könntest du mal ein paar Benchmark-Ergebnisse posten? Speziell interessieren mich:
6x6-6x10
3x10-3x20 (falls realistisch)
9x4-9x9 (falls realistisch)
natürlich alles auch gespiegelt.

**Comment by Necktschnagge** [comment]
Ich habe bisher nur einen auf Sekunden genaue Zeitmessung implementiert, die ggf auf oder abrundet:
damit gilt:
6x6:0s
6x7:0s
6x8:0s
6x9:1s
6x10:1s

3x10:0s
3x20:0s
9x4:0s
9x7:2s
9x8:5s
9x9:29s

EDIT: 3x10 / 10x3 solche Sachen machen bei meinem Algor _quasi_ keinen Unterschied. Der Algorithmus sortiert die Seitenlängen der Größe, da mit umgekehrter Eingabe er sehr sehr langsam wäre. (aber das sind technische Details vom Algorithmus) 

Ich habe die kompilierte Datei mal angehangen:
[Neuer ZIP-komprimierter Ordner.zip](https://github.com/Necktschnagge/cpp-course-project-01/files/966981/Neuer.ZIP-komprimierter.Ordner.zip)

**Comment by Necktschnagge** [comment]
gerechnet bei 2.6 GHz
(auch wenn ich mir nicht sicher bin, in wiefern das gegenüber der Speicherzugriffszeiten so ins Gewicht fällt, da das Programm schon bei 9x9 mit 50MB Speicherauslastung arbeitet)

**Comment by Necktschnagge** [comment]
Ich glaube fast Jorams Implementation in Phython ist **noch** schneller, habe aber noch nicht verglichen aus N/A / technischen Gründen. Ich müsste noch kritischen Code optimieren (hab aber auch irgednwie keine Lust dazu).
@Shildifreak falls du Lust hast, die executable rechnet aber nur bis long long int oder so...

**Comment by Necktschnagge** [comment]
@MaxMatti Wie sehen eigentlich deine Programmlaufzeiten aus?
bzw. hast du deinen Algorithmus nochmal verändert?
Würdest du ihn mal in einen eigenen Branch pushen oder darf ich deine Datei pushen, die du mir im Chat geschickt hast?

Ich würde demnächst (vielleicht nach nächster Stunde) auch meine Musterlösung hineinstellen.

**Comment by MaxMatti** [comment]
Meine Laufzeiten sind besser als die zuletzt geposteten, aber noch nicht so gut wie deine. Ich habe vor, (mehr) Caching einzubauen, um das zu verbessern. Aktuell habe ich Rekursives Backtracking mit einer Heuristik, die schneller Abbrechen verursacht (was ich auch seit dem letzten verbessert habe).
Du kannst die Datei gerne hochladen.
